site_name: Test DocsMK Project And Deploy To Github Page

nav:
  - Home: index.md
  - About: about.md
  - User Guide: 
      - Getting Started: user-guide/getting-started.md
      - Configuration: user-guide/configuration-option.md
  - Table: table.md
  - Code Block: codeblock.md
  - GT:
    - Support System: '!include ./support_system/mkdocs.yml'
    - Promotion: '!include ./promotion/mkdocs.yml'
    - Passport: '!include ./passport/mkdocs.yml'

plugins:
  - monorepo
 
theme: readthedocs

prev_next_buttons_location: bottom
