site_name: Passport

nav:
  - Overview: overview.md
  - Login Gateway: logingw.md
  - Login Widget: loginwg.md
  - User Guide:
    - Getting Started: userguide/getting-started.md
    - Configuration: userguide/configuration-option.md
